print("Peeranat")
print("Ponsiri")
print("PP")
print ("Chonradsadornumrung")
print("male")
print("17 years old")
print("25/09/2547")
print("170 cm")
print("50 kg")
print("football")
# Peeranat Ponsiri No.17